version: '3'
services:

    llt-web:
        build: ./web-client
        image: llt-frontend:latest
        expose:
            - "80"
        ports:
            - "80:80"
        depends_on:
            - llt-server
        links:
            - llt-server
    
    llt-server:
        build: ./server
        image: llt-backend:latest
        expose:
            - "8000"
        depends_on:
            - llt-db
        links:
            - llt-db
    

    llt-db:
        image: mysql:latest
        expose:
            - "3306"
        entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=llt-db



